### ISSUE TITLE
respect the platform default browser

### ISSUE THREAD

**Issue by ferrybig** [Chris2011/nb-git-open-in-external-repoviewer#42]
At my platform (Windows 10), Google Chrome is selected as the default browser, but this plugin keeps opening files in internet explorer

**Comment by Chris2011** [comment]
This is not related to this plugin, I think. The problem is that NetBeans doesn't care about the default system browser. When I change the option -> general -> web browser from <Default System Browser> to Chrome, everything works fine. When I change it back, it will open IE again.

If you click on edit behind the dropDown list, you can see, that the default browser is always IE. If you change it and reopen it, it will jump to IE again.

So change the browser to whatever you want (For me I changed it to Chrome) and everything works as expected. I will not fix this because it uses a NetBeans core feature (Default browser) which seems broken here.
